import { supabase } from "../lib/supabase";
const COUNT_COLUMNS="id, customer_id, counted_on, status, notes, created_by, created_at, updated_by, updated_at, completed_by, completed_at, deleted_by, deleted_at, deletion_reason, last_correction_reason, customers(id, customer_name, emirate)";
const ITEM_COLUMNS="id, count_id, assay_id, product_id, reference_lot_id, material_type, lot_number, normalized_lot_number, quantity, expiry_date, verification_status, assay_name_snapshot, product_code_snapshot, product_name_snapshot, matching_import_id, notes, display_order";
const LINK_COLUMNS="id, count_id, parent_item_id, child_item_id, relationship_type";
const EVENT_COLUMNS="id, count_id, event_type, reason, item_count, event_data, performed_by, performed_at";

export async function getBioplexCustomers(){const {data,error}=await supabase.from("instruments").select("customer_id, instrument_name, customers(id, customer_name, emirate, is_active)").eq("is_active",true).ilike("instrument_name","%bioplex%").not("customer_id","is",null);if(error)throw error;return Array.from(new Map((data??[]).filter((row)=>row.customers?.is_active).map((row)=>[String(row.customer_id),{id:String(row.customer_id),name:row.customers.customer_name,emirate:row.customers.emirate??""}])).values()).sort((a,b)=>a.name.localeCompare(b.name));}
export async function getBioplexCounts({includeDeleted=false}={}){let query=supabase.from("bioplex_counts").select(COUNT_COLUMNS);if(!includeDeleted)query=query.is("deleted_at",null);const {data,error}=await query.order("counted_on",{ascending:false}).order("created_at",{ascending:false});if(error)throw error;const ids=(data??[]).map((row)=>row.id);if(!ids.length)return[];const {data:items,error:itemError}=await supabase.from("bioplex_count_items").select("id, count_id").in("count_id",ids);if(itemError)throw itemError;const counts=(items??[]).reduce((map,row)=>map.set(row.count_id,(map.get(row.count_id)??0)+1),new Map());return(data??[]).map((row)=>({...row,itemCount:counts.get(row.id)??0}));}
export async function getBioplexCount(countId){const id=Number(countId);if(!Number.isFinite(id))throw new Error("Invalid BioPlex count ID.");const [{data:count,error},{data:items,error:itemError},{data:links,error:linkError},{data:events,error:eventError}]=await Promise.all([supabase.from("bioplex_counts").select(COUNT_COLUMNS).eq("id",id).single(),supabase.from("bioplex_count_items").select(ITEM_COLUMNS).eq("count_id",id).order("display_order"),supabase.from("bioplex_count_item_links").select(LINK_COLUMNS).eq("count_id",id),supabase.from("bioplex_count_events").select(EVENT_COLUMNS).eq("count_id",id).order("performed_at",{ascending:false})]);if(error)throw error;if(itemError)throw itemError;if(linkError)throw linkError;if(eventError)throw eventError;return{count,items:items??[],links:links??[],events:events??[]};}
function itemPayload(item,index){const quantity=item.quantity===""||item.quantity===null||item.quantity===undefined?null:Number(item.quantity);return{clientKey:item.clientKey,assayId:item.assayId||null,productId:item.productId||null,referenceLotId:item.referenceLotId||null,materialType:item.materialType,lotNumber:String(item.lotNumber??"").trim(),quantity,expiryDate:item.expiryDate||null,verificationStatus:item.verificationStatus||"Matched",assayName:String(item.assayName??"").trim(),productCode:String(item.productCode??"").trim()||null,productName:String(item.productName??"").trim(),matchingImportId:item.matchingImportId||null,notes:String(item.notes??"").trim()||null,displayOrder:index};}
export async function saveBioplexCount(payload){const {data,error}=await supabase.rpc("save_bioplex_count",{p_count_id:payload.countId?Number(payload.countId):null,p_customer_id:Number(payload.customerId),p_counted_on:payload.countedOn,p_notes:String(payload.notes??""),p_status:payload.status,p_items:payload.items.map(itemPayload),p_links:payload.links??[],p_correction_reason:String(payload.correctionReason??"")||null});if(error)throw error;return Number(data);}
export async function deleteBioplexCount(id,reason){const {data,error}=await supabase.rpc("soft_delete_bioplex_count",{p_count_id:Number(id),p_reason:String(reason??"")});if(error)throw error;return Number(data);}
export async function restoreBioplexCount(id,reason){const {data,error}=await supabase.rpc("restore_bioplex_count",{p_count_id:Number(id),p_reason:String(reason??"")});if(error)throw error;return Number(data);}
export async function recordBioplexExport(id,type,filename,settings={}){const {data,error}=await supabase.rpc("record_bioplex_export",{p_count_id:Number(id),p_export_type:type,p_filename:filename,p_settings:settings});if(error)throw error;return Number(data);}
export async function getBioplexProducts(materialType){const {data,error}=await supabase.from("bioplex_products").select("id, assay_id, material_type, product_code, product_name, display_order, bioplex_assays(id, assay_name)").eq("material_type",materialType).eq("is_active",true).order("display_order").order("product_name");if(error)throw error;return data??[];}
export async function getBioplexCustomerHistory(customerId){const id=Number(customerId);const {data:customer,error:customerError}=await supabase.from("customers").select("id, customer_name, emirate, is_active").eq("id",id).single();if(customerError)throw customerError;const {data:counts,error}=await supabase.from("bioplex_counts").select(COUNT_COLUMNS).eq("customer_id",id).in("status",["Completed","Exported"]).is("deleted_at",null).order("counted_on",{ascending:false});if(error)throw error;const ids=(counts??[]).map((row)=>row.id);let items=[];if(ids.length){const result=await supabase.from("bioplex_count_items").select(ITEM_COLUMNS).in("count_id",ids).order("display_order");if(result.error)throw result.error;items=result.data??[];}const byCount=items.reduce((map,row)=>{const arr=map.get(row.count_id)??[];arr.push(row);map.set(row.count_id,arr);return map;},new Map());return{customer:{id:String(customer.id),name:customer.customer_name,emirate:customer.emirate??""},visits:(counts??[]).map((count)=>({count,items:byCount.get(count.id)??[]}))};}
