import SelectInput from "../components/ui/SelectInput";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowUp, ChevronDown, ChevronRight, Plus, Trash2 } from "lucide-react";
import { findBioplexMatches } from "../services/bioplexMatching";
import { getBioplexCount, getBioplexCustomers, saveBioplexCount } from "../services/bioplexInventory";
import { formatBioplexDate, localDateOnly } from "../utils/bioplexDates";
import { buildBioplexInventoryGroups } from "../utils/bioplexInventoryGrouping";
const inputClass="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 outline-none focus:border-blue-500";
const makeKey=()=>crypto.randomUUID();
const CONSUMABLE_NAMES=["Detector Calibrator","Detector Clean","Sheath Fluid","Buffer","RVs"];
function consumableItem(productName,index){return{clientKey:makeKey(),assayId:null,productId:null,referenceLotId:null,materialType:"consumable",lotNumber:"",quantity:"",expiryDate:"",verificationStatus:"Manual",assayName:"Consumables",productCode:"",productName,matchingImportId:null,notes:"",displayOrder:10000+index};}
function ensureConsumables(currentItems){const existing=new Set(currentItems.filter((item)=>item.materialType==="consumable").map((item)=>String(item.productName||"").trim().toLowerCase()));const missing=CONSUMABLE_NAMES.filter((name)=>!existing.has(name.toLowerCase())).map(consumableItem);return missing.length?[...currentItems,...missing]:currentItems;}
function itemFrom(row,quantity){return{clientKey:makeKey(),assayId:row.assay_id,productId:row.product_id,referenceLotId:row.lot_id,materialType:row.material_type,lotNumber:row.lot_number,quantity,expiryDate:row.expiry_date||"",verificationStatus:"Matched",assayName:row.assay_name,productCode:row.product_code||"",productName:row.product_name||`${row.assay_name} ${row.material_type}`,matchingImportId:row.source_import_id,notes:""};}
function relatedFrom(row){return{clientKey:makeKey(),assayId:row.assay_id,productId:null,referenceLotId:row.related_lot_id,materialType:row.related_material_type,lotNumber:row.related_lot_number,quantity:"0",expiryDate:row.related_expiry_date||"",verificationStatus:"Matched",assayName:row.assay_name,productCode:"",productName:`${row.assay_name} ${row.related_material_type}`,matchingImportId:row.source_import_id,notes:""};}
const uniqueLinks=(existing,additions)=>additions.filter((candidate)=>!existing.some((link)=>link.parentKey===candidate.parentKey&&link.childKey===candidate.childKey&&link.relationshipType===candidate.relationshipType));
const directIncrement=(raw)=>raw===""?1:Number(raw);
export default function BioplexInventoryFormPage(){
 const{sessionId}=useParams();const navigate=useNavigate();const editing=Boolean(sessionId);const[customers,setCustomers]=useState([]);const[customerId,setCustomerId]=useState("");const[countedOn,setCountedOn]=useState(localDateOnly());const[notes,setNotes]=useState("");const[correctionReason,setCorrectionReason]=useState("");const[previousStatus,setPreviousStatus]=useState("Draft");const[items,setItems]=useState([]);const[links,setLinks]=useState([]);const[lookup,setLookup]=useState("");const[lookupQuantity,setLookupQuantity]=useState("");const[candidates,setCandidates]=useState([]);const[search,setSearch]=useState("");const[filter,setFilter]=useState("All");const[collapsed,setCollapsed]=useState(new Set(["Consumables"]));const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[lookupError,setLookupError]=useState("");const customerRef=useRef(null);const lotRef=useRef(null);
 useEffect(()=>{Promise.all([getBioplexCustomers(),editing?getBioplexCount(sessionId):null]).then(([options,record])=>{setCustomers(options);if(!record){setItems(ensureConsumables([]));return;}setCustomerId(String(record.count.customer_id));setCountedOn(record.count.counted_on);setNotes(record.count.notes||"");setPreviousStatus(record.count.status);setItems(ensureConsumables(record.items.map((item)=>({clientKey:String(item.id),assayId:item.assay_id,productId:item.product_id,referenceLotId:item.reference_lot_id,materialType:item.material_type,lotNumber:item.lot_number||"",quantity:item.quantity??"",expiryDate:item.expiry_date||"",verificationStatus:item.verification_status,assayName:item.assay_name_snapshot,productCode:item.product_code_snapshot||"",productName:item.product_name_snapshot,matchingImportId:item.matching_import_id,notes:item.notes||""}))));const keys=new Map(record.items.map((item)=>[item.id,String(item.id)]));setLinks(record.links.map((link)=>({parentKey:keys.get(link.parent_item_id),childKey:keys.get(link.child_item_id),relationshipType:link.relationship_type})));}).catch((e)=>setError(e.message));},[editing,sessionId]);
 const assaySections=useMemo(()=>{const grouped=buildBioplexInventoryGroups(items,links);const byAssay=new Map();const ensure=(name)=>{if(!byAssay.has(name))byAssay.set(name,{name,groups:[],standalone:[],items:[]});return byAssay.get(name);};grouped.reagentGroups.forEach((group)=>{const section=ensure(group.root.assayName);section.groups.push(group);section.items.push(group.root,...group.children.map((entry)=>entry.item));});grouped.standalone.forEach((item)=>{const section=ensure(item.assayName);section.standalone.push(item);section.items.push(item);});return[...byAssay.values()].map((section)=>({...section,items:[...new Map(section.items.map((item)=>[item.clientKey,item])).values()]})).sort((a,b)=>a.name.localeCompare(b.name));},[items,links]);
 const visibleSections=useMemo(()=>{const q=search.trim().toUpperCase();return assaySections.map((section)=>({...section,groups:section.groups.filter((group)=>matches(group.root,q,filter)||group.children.some((entry)=>matches(entry.item,q,filter))),standalone:section.standalone.filter((item)=>matches(item,q,filter))})).filter((section)=>section.groups.length||section.standalone.length);},[assaySections,search,filter]);
 function addLinks(additions){if(additions.length)setLinks((current)=>[...current,...uniqueLinks(current,additions)]);}
 function addDirectResult(first,results){const entered=lookupQuantity;const increment=directIncrement(entered);if(!Number.isInteger(increment)||increment<0)throw new Error("Quantity must be a whole number of zero or greater.");const existing=items.find((item)=>item.referenceLotId===first.lot_id&&item.materialType===first.material_type);if(existing){setItems((current)=>current.map((item)=>item.clientKey===existing.clientKey?{...item,quantity:String((item.quantity===""?0:Number(item.quantity))+increment)}:item));attachExisting(existing,first,results);return;}const main=itemFrom(first,String(increment));const additions=[];const newItems=[main];if(first.material_type==="kit"){for(const row of results.filter((row)=>row.relationship_type==="kit_calibrator"&&row.related_material_type==="calibrator"&&row.related_lot_id)){let child=items.find((item)=>item.referenceLotId===row.related_lot_id&&item.materialType==="calibrator")||newItems.find((item)=>item.referenceLotId===row.related_lot_id);if(!child){child=relatedFrom(row);newItems.push(child);}additions.push({parentKey:main.clientKey,childKey:child.clientKey,relationshipType:"kit_calibrator"});}items.filter((item)=>item.materialType==="qc"&&item.assayId===first.assay_id).forEach((qc)=>additions.push({parentKey:main.clientKey,childKey:qc.clientKey,relationshipType:"kit_qc"}));}
 if(first.material_type==="calibrator"){results.filter((row)=>row.relationship_type==="kit_calibrator"&&row.related_material_type==="kit").forEach((row)=>{let reagent=items.find((item)=>item.referenceLotId===row.related_lot_id&&item.materialType==="kit");if(!reagent){reagent=relatedFrom({...row,related_material_type:"kit"});newItems.push(reagent);}additions.push({parentKey:reagent.clientKey,childKey:main.clientKey,relationshipType:"kit_calibrator"});});}
 if(first.material_type==="qc")items.filter((item)=>item.materialType==="kit"&&item.assayId===first.assay_id).forEach((kit)=>additions.push({parentKey:kit.clientKey,childKey:main.clientKey,relationshipType:"kit_qc"}));setItems((current)=>[...current,...newItems]);addLinks(additions);}
 function attachExisting(existing,first,results){if(first.material_type==="calibrator")addLinks(items.filter((item)=>item.materialType==="kit"&&results.some((row)=>row.relationship_type==="kit_calibrator"&&row.related_lot_id===item.referenceLotId)).map((kit)=>({parentKey:kit.clientKey,childKey:existing.clientKey,relationshipType:"kit_calibrator"})));if(first.material_type==="qc")addLinks(items.filter((item)=>item.materialType==="kit"&&item.assayId===first.assay_id).map((kit)=>({parentKey:kit.clientKey,childKey:existing.clientKey,relationshipType:"kit_qc"})));}
 async function lookupLot(selected=null){const lot=lookup.trim();if(!lot){setLookupError("Enter a lot number.");lotRef.current?.focus();return;}try{setBusy(true);setLookupError("");const results=selected?.results||await findBioplexMatches(lot,"",false);const primaries=[...new Map(results.map((row)=>[`${row.lot_id}|${row.assay_id}|${row.material_type}`,row])).values()];if(!selected&&primaries.length>1){setCandidates(primaries.map((primary)=>({primary,results:results.filter((row)=>row.lot_id===primary.lot_id)})));return;}const choice=selected?.primary||primaries[0];if(!choice)throw new Error("Lot not found in active matching data.");addDirectResult(choice,selected?.results||results.filter((row)=>row.lot_id===choice.lot_id));setLookup("");setLookupQuantity("");setCandidates([]);}catch(e){setLookupError(e.message);lotRef.current?.focus();}finally{setBusy(false);}}
 function updateItem(key,changes){setItems((current)=>current.map((item)=>item.clientKey===key?{...item,...changes}:item));}function removeItem(key){setItems((current)=>current.filter((item)=>item.clientKey!==key));setLinks((current)=>current.filter((link)=>link.parentKey!==key&&link.childKey!==key));}
 async function save(status){if(!customerId){setError("Select a BioPlex customer.");customerRef.current?.focus();return;}if(!items.length){setError("Add at least one stock item.");lotRef.current?.focus();return;}const missing=items.find((item)=>status==="Completed"&&(item.quantity===""||item.quantity===null));if(missing){setError("Enter every quantity before completing the count.");const section=missing.assayName;setCollapsed((current)=>{const next=new Set(current);next.delete(section);return next;});requestAnimationFrame(()=>document.querySelector(`[data-key="${CSS.escape(missing.clientKey)}"]`)?.focus());return;}if(["Completed","Exported"].includes(previousStatus)&&!correctionReason.trim()){setError("Enter a correction reason.");document.querySelector("[data-correction]")?.focus();return;}try{setBusy(true);const id=await saveBioplexCount({countId:sessionId,customerId,countedOn,notes,status,items,links,correctionReason});navigate(`/bioplex-inventory/${id}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="mx-auto max-w-6xl space-y-5 pb-28 md:pb-6"><header><p className="text-sm text-blue-400">BioPlex Inventory</p><h1 className="text-3xl font-semibold">{editing?"Edit stock count":"New stock count"}</h1></header>{error&&<div className="rounded-xl border border-red-900 bg-red-950/40 p-4 text-red-300" role="alert">{error}</div>}<section className="grid gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-5 md:grid-cols-2"><label>Customer<SelectInput ref={customerRef} className={`${inputClass} mt-2`} value={customerId} onChange={(e)=>setCustomerId(e.target.value)}><option value="">Select customer</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.name}{customer.emirate?`, ${customer.emirate}`:""}</option>)}</SelectInput></label><label>Count date<input type="date" className={`${inputClass} mt-2`} value={countedOn} onChange={(e)=>setCountedOn(e.target.value)}/><span className="mt-1 block text-xs text-slate-500">{formatBioplexDate(countedOn)}</span></label><label className="md:col-span-2">Notes<textarea rows={2} className={`${inputClass} mt-2`} value={notes} onChange={(e)=>setNotes(e.target.value)}/></label>{["Completed","Exported"].includes(previousStatus)&&<label className="md:col-span-2">Correction reason<textarea data-correction rows={2} className={`${inputClass} mt-2`} value={correctionReason} onChange={(e)=>setCorrectionReason(e.target.value)}/></label>}</section>
 <section className="rounded-2xl border border-blue-900 bg-blue-950/20 p-5"><h2 className="text-xl font-semibold">Add stock item</h2><p className="mt-1 text-sm text-slate-400">Enter a reagent, calibrator, or QC lot. The system identifies the type.</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_9rem_auto]"><input ref={lotRef} className={inputClass} value={lookup} onChange={(e)=>{setLookup(e.target.value);setCandidates([]);setLookupError("");}} placeholder="Any lot number"/><input type="number" min="0" step="1" className={`${inputClass} [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none`} value={lookupQuantity} onChange={(e)=>setLookupQuantity(e.target.value)} placeholder="Qty optional"/><button disabled={busy} onClick={()=>lookupLot()} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 disabled:opacity-50"><Plus size={17}/>Add</button></div>{lookupError&&<p className="mt-2 text-sm text-red-300" role="alert">{lookupError}</p>}{candidates.length>0&&<div className="mt-4 rounded-xl border border-amber-800 bg-amber-950/20 p-4"><p className="font-medium text-amber-200">Multiple active records match this lot. Choose one:</p><div className="mt-3 space-y-2">{candidates.map((candidate)=><button key={`${candidate.primary.lot_id}-${candidate.primary.assay_id}-${candidate.primary.material_type}`} onClick={()=>lookupLot(candidate)} className="flex w-full justify-between rounded-xl border border-slate-700 bg-slate-950 p-3 text-left"><span>{candidate.primary.assay_name}</span><span className="capitalize text-slate-400">{candidate.primary.material_type}</span></button>)}</div></div>}</section>
 <section className="sticky top-2 z-20 space-y-3 rounded-2xl border border-slate-700 bg-slate-900/95 p-3 backdrop-blur"><div className="grid gap-2 sm:grid-cols-[1fr_13rem]"><input type="search" className={inputClass} value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search assay, material, or lot"/><SelectInput className={inputClass} value={filter} onChange={(e)=>setFilter(e.target.value)}><option>All</option><option>Reagents</option><option>Calibrators</option><option>QC</option><option>Consumables</option><option>Missing quantity</option><option>Zero quantity</option></SelectInput></div><div className="flex gap-2 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button onClick={()=>{const name=visibleSections[0]?.name;if(name)document.getElementById(`assay-${slug(name)}`)?.scrollIntoView({behavior:"smooth",block:"start"});}} className="whitespace-nowrap rounded-lg border border-slate-700 px-3 py-1.5 text-sm">Jump to first match</button><button onClick={()=>setCollapsed(new Set(assaySections.map((s)=>s.name)))} className="whitespace-nowrap rounded-lg border border-slate-700 px-3 py-1.5 text-sm">Collapse all</button><button onClick={()=>setCollapsed(new Set())} className="whitespace-nowrap rounded-lg border border-slate-700 px-3 py-1.5 text-sm">Expand all</button></div></section>
 <section className="space-y-4">{visibleSections.map((section)=>{const isCollapsed=collapsed.has(section.name)&&!search;const entered=section.items.filter((item)=>item.quantity!==""&&item.quantity!==null).length;return <article id={`assay-${slug(section.name)}`} key={section.name} className="scroll-mt-40 rounded-2xl border border-slate-800 bg-slate-900"><button onClick={()=>setCollapsed((current)=>{const next=new Set(current);next.has(section.name)?next.delete(section.name):next.add(section.name);return next;})} className="flex w-full items-center justify-between gap-3 p-4 text-left"><span className="flex items-center gap-2">{isCollapsed?<ChevronRight/>:<ChevronDown/>}<strong>{section.name}</strong></span><span className={`rounded-full px-3 py-1 text-xs ${entered===section.items.length?"bg-emerald-950 text-emerald-300":"bg-amber-950 text-amber-300"}`}>{entered} of {section.items.length} entered</span></button>{!isCollapsed&&<div className="border-t border-slate-800 p-4"><div className="space-y-3">{section.groups.map((group)=><div key={group.root.clientKey} className="rounded-xl border border-slate-700 p-4"><Material item={group.root} update={updateItem} remove={removeItem}/>{group.children.map((entry)=><div key={entry.item.clientKey} className="mt-3 border-t border-slate-800 pt-3"><Material item={entry.item} update={updateItem} remove={removeItem} label={entry.relationshipType==="kit_qc"?"Assay QC":entry.shared?"Shared calibrator":"Matched calibrator"}/></div>)}</div>)}</div>{section.standalone.length>0&&<div className={`${section.name==="Consumables"?"grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5":"mt-3 space-y-3"}`}>{section.standalone.map((item)=><div key={item.clientKey} className="rounded-xl border border-dashed border-slate-700 p-4"><Material item={item} update={updateItem} remove={removeItem} label={section.name==="Consumables"?undefined:"Standalone material"}/></div>)}</div>}</div>}</article>;})}{!items.length&&<div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center text-slate-400">No stock items added.</div>}</section>
 <button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="fixed bottom-24 right-4 z-30 rounded-full border border-slate-700 bg-slate-900 p-3 shadow-xl md:bottom-6" aria-label="Back to top"><ArrowUp size={20}/></button><div className="fixed inset-x-0 bottom-0 z-30 flex justify-end gap-2 border-t border-slate-700 bg-slate-950/95 p-3 backdrop-blur md:static md:border-0 md:bg-transparent md:p-0"><Link to="/bioplex-inventory" className="mr-auto hidden items-center gap-2 text-sm text-slate-400 md:inline-flex"><ArrowLeft size={18}/>Back</Link><button disabled={busy} onClick={()=>save("Draft")} className="rounded-xl border border-blue-700 px-4 py-2 text-blue-300">Save draft</button><button disabled={busy} onClick={()=>save("Completed")} className="rounded-xl bg-emerald-600 px-4 py-2 font-medium">Complete count</button></div></div>;
}
function matches(item,q,filter){if(q&&!`${item.assayName} ${item.productName} ${item.lotNumber} ${item.materialType}`.toUpperCase().includes(q))return false;if(filter==="Reagents"&&item.materialType!=="kit")return false;if(filter==="Calibrators"&&item.materialType!=="calibrator")return false;if(filter==="QC"&&item.materialType!=="qc")return false;if(filter==="Consumables"&&item.materialType!=="consumable")return false;if(filter==="Missing quantity"&&item.quantity!==""&&item.quantity!==null)return false;if(filter==="Zero quantity"&&(item.quantity===""||item.quantity===null||item.quantity===undefined||Number(item.quantity)!==0))return false;return true;}
function slug(value){return String(value).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function Material({item,update,remove,label}){const consumable=item.materialType==="consumable";return <div><div className="flex items-start justify-between gap-3"><div>{label&&<p className="text-xs uppercase text-cyan-400">{label}</p>}<h3 className="font-semibold">{item.productName}</h3></div>{!consumable&&<button onClick={()=>remove(item.clientKey)} className="text-red-300" aria-label={`Remove ${item.productName}`}><Trash2 size={18}/></button>}</div><div className={`mt-3 grid gap-3 ${consumable?"grid-cols-1":"sm:grid-cols-4"}`}>{!consumable&&<><Read label="Type" value={item.materialType}/><Read label="Lot" value={item.lotNumber||"Not recorded"}/><Read label="Expiry" value={formatBioplexDate(item.expiryDate)||"Not recorded"}/></>}<label>Quantity<input data-key={item.clientKey} type="number" min="0" step="1" className={`${inputClass} mt-2 [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none`} value={item.quantity} onChange={(e)=>update(item.clientKey,{quantity:e.target.value})}/></label></div></div>;}
function Read({label,value}){return <div><p className="text-sm text-slate-500">{label}</p><p className="mt-2">{value}</p></div>;}
