import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Boxes, Check, Copy, ExternalLink, FlaskConical, Server, ShieldCheck, Users } from "lucide-react";
import { getCustomerSiteOverview } from "../services/customers";
import { formatDateOnly } from "../utils/dateDisplay";
export default function CustomerSiteOverviewPage({ canEdit }) {
  const { customerId } = useParams(); const [record, setRecord] = useState(null); const [error, setError] = useState(""); const [copiedEmail, setCopiedEmail] = useState(""); const copyTimerRef = useRef(null);
  useEffect(() => { getCustomerSiteOverview(customerId).then(setRecord).catch((loadError) => setError(loadError.message || "Unable to load customer site overview.")); return () => { if (copyTimerRef.current) window.clearTimeout(copyTimerRef.current); }; }, [customerId]); async function copyEmail(email) { try { await navigator.clipboard.writeText(email); setCopiedEmail(email); if (copyTimerRef.current) window.clearTimeout(copyTimerRef.current); copyTimerRef.current = window.setTimeout(() => setCopiedEmail(""), 1800); } catch { setError("Unable to copy the email address."); } }
  if (error) return <div className="rounded-xl border border-red-900 bg-red-950/40 p-4 text-red-300">{error}</div>;
  if (!record) return <div className="text-slate-400">Loading customer site overview...</div>;
  const { customer, instruments, unity, eqas } = record;
  return <div className="mx-auto max-w-7xl space-y-5"><Link to="/customers" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={18}/>Back to customers</Link><header className="rounded-2xl border border-slate-800 bg-gradient-to-br from-fuchsia-950/60 via-slate-900 to-blue-950/60 p-6"><p className="text-sm text-blue-400">Customer Site Overview</p><div className="mt-1 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-semibold">{customer.customer_name}</h1><p className="mt-1 text-slate-400">{customer.emirate || "Location not recorded"}</p></div>{canEdit && <Link to={`/customers/${customer.id}/edit`} className="rounded-xl border border-blue-700 px-4 py-2 text-blue-300">Edit customer</Link>}</div>{(customer.is_iso_eiac_accredited || customer.is_cap_accredited) && <div className="mt-5 rounded-2xl border border-emerald-700/70 bg-emerald-950/30 p-4"><h2 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-emerald-300"><ShieldCheck size={19}/>Laboratory accreditation</h2><div className="mt-3 flex flex-wrap gap-3">{customer.is_iso_eiac_accredited && <div className="rounded-xl border border-blue-700 bg-blue-950/70 px-4 py-3"><p className="font-semibold text-blue-200">ISO/EIAC</p><p className="mt-1 text-sm text-blue-300">Accreditation No. {customer.iso_eiac_accreditation_number}</p></div>}{customer.is_cap_accredited && <div className="rounded-xl border border-violet-700 bg-violet-950/70 px-4 py-3"><p className="font-semibold text-violet-200">CAP Accredited</p></div>}</div></div>}</header>
    {customer.customer_contacts?.length > 0 && <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><Users size={20}/>Contacts</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{customer.customer_contacts.map((contact) => <article key={contact.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><h3 className="font-semibold">{contact.name}</h3><p className="text-sm text-blue-300">{contact.designation}</p>{contact.phone_number && <p className="mt-2 text-sm">{contact.phone_number}</p>}{contact.email && <div className="mt-2 flex items-center gap-2"><p className="min-w-0 flex-1 break-all text-sm text-slate-400">{contact.email}</p><button type="button" onClick={() => copyEmail(contact.email)} className="inline-flex shrink-0 items-center gap-1 rounded-lg border border-slate-700 px-2 py-1.5 text-xs text-slate-300 hover:border-blue-600 hover:text-blue-300" aria-label={`Copy ${contact.email}`}>{copiedEmail === contact.email ? <Check size={14}/> : <Copy size={14}/>} {copiedEmail === contact.email ? "Copied" : "Copy"}</button></div>}</article>)}</div></section>}
    {instruments.length > 0 && <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-semibold"><Boxes size={20}/>Installed instruments</h2><span className="text-sm text-slate-400">{instruments.length} active</span></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{instruments.map((instrument) => <article key={instrument.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><h3 className="font-semibold">{instrument.instrument_name}</h3><dl className="mt-3 space-y-2 text-sm"><Info label="Serial number" value={instrument.serial_number || "Not recorded"}/><Info label="Installation date" value={formatDateOnly(instrument.installation_date)}/></dl>{canEdit && <Link to={`/assets/${instrument.id}/edit`} className="mt-4 inline-flex items-center gap-2 text-sm text-blue-300">View in Assets<ExternalLink size={15}/></Link>}</article>)}</div></section>}
    {(unity.length > 0 || eqas.length > 0) && <section className="grid gap-4 lg:grid-cols-2">{unity.length > 0 && <div className="rounded-2xl border border-cyan-900 bg-cyan-950/20 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><Server size={20}/>Unity Real Time</h2><div className="mt-4 space-y-3">{unity.map((installation) => <article key={installation.id} className="rounded-xl border border-cyan-900 bg-slate-950 p-4"><h3 className="font-semibold">{installation.installation_name || "Unity installation"}</h3><dl className="mt-3 space-y-2 text-sm"><Info label="Primary ID" value={installation.primary_id}/><Info label="License status" value={installation.unity_rt_license_status || "Not recorded"}/><Info label="Expiry" value={formatDateOnly(installation.unity_rt_expiry_date)}/><Info label="Connectivity" value={installation.connectivity_type || "None"}/></dl>{canEdit && <Link to={`/unity-real-time/${installation.id}/edit`} className="mt-4 inline-flex items-center gap-2 text-sm text-blue-300">View in Unity Real Time<ExternalLink size={15}/></Link>}</article>)}</div></div>}{eqas.length > 0 && <div className="rounded-2xl border border-violet-900 bg-violet-950/20 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold"><FlaskConical size={20}/>EQAS Online</h2><div className="mt-4 space-y-3">{eqas.map((item) => <article key={item.id} className="rounded-xl border border-violet-900 bg-slate-950 p-4"><h3 className="font-semibold">{item.lab_name || "EQAS laboratory"}</h3><dl className="mt-3 space-y-2 text-sm"><Info label="Lab Number" value={item.lab_number || "Not recorded"}/><Info label="QCnet ID" value={item.qcnet_id || "Not recorded"}/></dl>{canEdit && <Link to={`/eqas-online/${item.id}/edit`} className="mt-4 inline-flex items-center gap-2 text-sm text-blue-300">View in EQAS Online<ExternalLink size={15}/></Link>}</article>)}</div></div>}</section>}
  </div>;
}
function Info({ label, value }) { return <div><dt className="text-slate-500">{label}</dt><dd>{value || "Not recorded"}</dd></div>; }
