const MAX_FILE_BYTES = 25 * 1024 * 1024;
const EMPTY_MARKERS = new Set(["", "NA", "N/A", "/", "PRINTED"]);

function dateResult(value) {
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    const year=value.getFullYear(), month=value.getMonth()+1, day=value.getDate();
    return { value:`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`, raw:`${String(day).padStart(2,"0")}/${String(month).padStart(2,"0")}/${year}`, issue:"" };
  }
  const raw=String(value??"").trim();
  if (!raw) return {value:null,raw:"",issue:""};
  const match=/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2}|\d{4})$/.exec(raw);
  if (!match) return {value:null,raw,issue:"INVALID_DATE"};
  let day=Number(match[1]), month=Number(match[2]), year=Number(match[3]);
  if (year<100) year+=year>=70?1900:2000;
  const candidate=new Date(Date.UTC(year,month-1,day));
  if(candidate.getUTCFullYear()!==year||candidate.getUTCMonth()!==month-1||candidate.getUTCDate()!==day||year<1990||year>2100)return{value:null,raw,issue:"INVALID_DATE"};
  return{value:`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`,raw,issue:""};
}
function text(value){if(value instanceof Date)return dateResult(value).raw;return String(value??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim();}
function upper(value){return text(value).toUpperCase();}
export function normalizeLot(value){const normalized=upper(value);return EMPTY_MARKERS.has(normalized)?"":normalized;}
export function dateToIso(value){return dateResult(value);}
function headerIndex(headers,tests){return headers.findIndex((value)=>tests.some((test)=>test.test(value)));}
function allHeaderIndexes(headers,tests){return headers.map((value,index)=>tests.some((test)=>test.test(value))?index:-1).filter((index)=>index>=0);}
function sourceValues(row){return{cells:row.map((value)=>value instanceof Date?dateResult(value).value:text(value))};}
function splitCellLots(value){const raw=normalizeLot(value);return raw?raw.split(/\s*[,;]\s*|\s+\/\s+/).map(normalizeLot).filter(Boolean):[];}
function unique(values){return[...new Set(values.filter(Boolean))];}
function detectSections(rows){const found=[];rows.forEach((row,index)=>row.forEach((value)=>{const v=upper(value);if(v==="KITS"||v==="CONTROLS")found.push({type:v,start:index});}));found.sort((a,b)=>a.start-b.start);return found.map((section,index)=>({...section,end:found[index+1]?.start??rows.length}));}
function status(issues){return issues.includes("MISSING_LOT")||issues.includes("INVALID_DATE")||issues.includes("UNREADABLE_SECTION")?"Invalid":issues.length?"Warning":"Valid";}
function buildRow({sheetName,rowIndex,sectionType,assayName,materialType,lot,release,expiry,ccCode,relatedLot="",relatedMaterialType=null,row,issues=[]}){const codes=[...new Set(issues.filter(Boolean))];const reviewStatus=status(codes);return{sheetName,sourceRowNumber:rowIndex+1,sectionType,assayNameRaw:assayName,assayNameNormalized:upper(assayName),materialType,ccCodeRaw:text(ccCode),productCodeRaw:"",lotNumberRaw:lot,lotNumberNormalized:normalizeLot(lot),releaseDateRaw:release.raw,releaseDate:release.value,expiryDateRaw:expiry.raw,expiryDate:expiry.value,relatedLotRaw:relatedLot,relatedLotNormalized:normalizeLot(relatedLot),relatedMaterialType,sourceValues:sourceValues(row),issueCodes:codes,reviewStatus,proposedAction:reviewStatus==="Invalid"?"Review":"Create",reviewMessage:codes.join(", ")};}
function parseSection(sheetName,rows,section){const assayName=/^SHEET\d*$/i.test(sheetName)?"":sheetName;let h=-1;for(let i=section.start+1;i<Math.min(section.end,section.start+8);i+=1){const joined=(rows[i]??[]).map(upper).join("|");if(joined.includes("BN")&&(joined.includes("EXPIR")||joined.includes("RELEASE"))){h=i;break;}}if(h<0)return[buildRow({sheetName,rowIndex:section.start,sectionType:section.type,assayName,materialType:section.type==="KITS"?"kit":"qc",lot:"",release:dateResult(null),expiry:dateResult(null),ccCode:"",row:rows[section.start]??[],issues:["UNREADABLE_SECTION","MISSING_LOT"]})];const headers=(rows[h]??[]).map(upper);const output=[];const ccIndex=headerIndex(headers,[/CC CODE/,/DC CODE/]);if(section.type==="KITS"){const kitIndex=headerIndex(headers,[/KIT BN/,/KIT BATCH/]);const kitRelease=headerIndex(headers,[/KIT RELEASE/]);const kitExpiry=headerIndex(headers,[/KIT EXPIR/]);const calSetIndex=headerIndex(headers,[/CALIBRATOR SET BN/]);const calRelease=headerIndex(headers,[/CALIBRATOR SET RELEASE/]);const calExpiry=headerIndex(headers,[/CALIBRATOR SET EXPIR/]);const cdIndexes=allHeaderIndexes(headers,[/CALIBRATOR CD BN/]);for(let r=h+1;r<section.end;r+=1){const row=rows[r]??[];const kit=normalizeLot(row[kitIndex]);const calSet=normalizeLot(row[calSetIndex]);const cds=unique(cdIndexes.flatMap((index)=>splitCellLots(row[index])));const calibrators=unique([calSet,...cds]);if(!kit&&!calibrators.length)continue;const kr=dateResult(row[kitRelease]),ke=dateResult(row[kitExpiry]),cr=dateResult(row[calRelease]),ce=dateResult(row[calExpiry]);const commonIssues=[kr.issue,ke.issue,cr.issue,ce.issue].filter(Boolean);if(kit){if(calibrators.length)calibrators.forEach((cal)=>output.push(buildRow({sheetName,rowIndex:r,sectionType:section.type,assayName,materialType:"kit",lot:kit,release:kr,expiry:ke,ccCode:row[ccIndex],relatedLot:cal,relatedMaterialType:"calibrator",row,issues:commonIssues})));else output.push(buildRow({sheetName,rowIndex:r,sectionType:section.type,assayName,materialType:"kit",lot:kit,release:kr,expiry:ke,ccCode:row[ccIndex],row,issues:[...commonIssues,"MISSING_CALIBRATOR"]}));}else calibrators.forEach((cal)=>output.push(buildRow({sheetName,rowIndex:r,sectionType:section.type,assayName,materialType:"calibrator",lot:cal,release:cr,expiry:ce,ccCode:row[ccIndex],row,issues:commonIssues})));}}
else{const setIndex=headerIndex(headers,[/CONTROL SET BN/,/SET BN/]);const relIndex=headerIndex(headers,[/SET RELEASE/]);const expIndex=headerIndex(headers,[/SET EXPIR/]);const cdIndexes=allHeaderIndexes(headers,[/CONTROL CD BN/,/CONTROL CB BN/]);for(let r=h+1;r<section.end;r+=1){const row=rows[r]??[];const setLot=normalizeLot(row[setIndex]);const cds=unique(cdIndexes.flatMap((index)=>splitCellLots(row[index])));const lots=unique([setLot,...cds]);if(!lots.length)continue;const release=dateResult(row[relIndex]),expiry=dateResult(row[expIndex]);const issues=[release.issue,expiry.issue].filter(Boolean);lots.forEach((lot)=>output.push(buildRow({sheetName,rowIndex:r,sectionType:section.type,assayName,materialType:"qc",lot,release,expiry,ccCode:row[ccIndex],row,issues})));}}
return output;}
function classifyDuplicates(rows){const seen=new Map();return rows.map((row)=>{const key=[row.assayNameNormalized,row.materialType,row.lotNumberNormalized,row.relatedMaterialType??"",row.relatedLotNormalized??""].join("|");if(!row.lotNumberNormalized||row.reviewStatus==="Invalid")return row;if(seen.has(key))return{...row,reviewStatus:"Exact Duplicate",proposedAction:"Skip Duplicate",issueCodes:[...row.issueCodes,"DUPLICATE_IN_FILE"],reviewMessage:`Exact duplicate of ${seen.get(key)}.`};seen.set(key,`${row.sheetName}:${row.sourceRowNumber}`);return row;});}
export async function parseBioplexMatchingWorkbook(file){if(!file)throw new Error("Select an .xlsx matching workbook.");if(!/\.xlsx$/i.test(file.name))throw new Error("Only .xlsx matching workbooks are accepted.");if(file.size>MAX_FILE_BYTES)throw new Error("The workbook exceeds the 25 MB safety limit.");const{default:readExcelFile}=await import("read-excel-file/browser");const sheets=await readExcelFile(file);const parsed=[];for(const sheet of sheets){for(const section of detectSections(sheet.data??[]))parsed.push(...parseSection(sheet.sheet,sheet.data??[],section));}const rows=classifyDuplicates(parsed);return{fileName:file.name,sheetCount:sheets.length,rows,summary:summarizeImportRows(rows)};}
export function summarizeImportRows(rows){const summary={total:rows.length,valid:0,warning:0,exactDuplicate:0,possibleDuplicate:0,conflict:0,invalid:0,excluded:0};for(const row of rows){const key={Valid:"valid",Warning:"warning","Exact Duplicate":"exactDuplicate","Possible Duplicate":"possibleDuplicate",Conflict:"conflict",Invalid:"invalid",Excluded:"excluded"}[row.reviewStatus];if(key)summary[key]+=1;}return summary;}
